//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AllNewsTb
{
    public AllNewsTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int AllNewsID { get; set; }
    public string Photo { get; set; }
    public string Title { get; set; }
    public string body { get; set; }
    public string caption { get; set; }
    public string AllNewsTbID { get; set; }
    public string video { get; set; }
    public string Admin_Name { get; set; }
    public string Date_time { get; set; }
    public string Photo2 { get; set; }
    public string Photo3 { get; set; }
    public string Likes { get; set; }
    public string Category { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class Breaking_NewsTb
{
    public Breaking_NewsTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int Breaking_NewsID { get; set; }
    public string Photo { get; set; }
    public string Video { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string Admin_Photo { get; set; }
    public string Admin_Name { get; set; }
    public string Time_and_Date { get; set; }
    public string Likes_and_comments { get; set; }
    public string Views { get; set; }
    public string Breaking_NewsTbID { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class commentTb
{
    public commentTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int commentID { get; set; }
    public string username { get; set; }
    public string Her_Comment { get; set; }
    public string His_comment { get; set; }
    public string client_comment { get; set; }
    public string body_commet { get; set; }
    public string Url { get; set; }
    public string commentTbId { get; set; }
    public string Other_isues { get; set; }
    public string Date_Time { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class Connection_Tb
{
    public int ContentID { get; set; }
    public Nullable<int> SportId { get; set; }
    public Nullable<int> HealthID { get; set; }
    public Nullable<int> breakingNewsID { get; set; }
    public Nullable<int> SapeleNewsID { get; set; }
    public Nullable<int> WisdomQuoteID { get; set; }
    public Nullable<int> Politices { get; set; }
    public Nullable<int> Int { get; set; }

    public virtual Breaking_NewsTb Breaking_NewsTb { get; set; }
    public virtual HealthTb HealthTb { get; set; }
    public virtual PoliticsTb PoliticsTb { get; set; }
    public virtual QuotesTb QuotesTb { get; set; }
    public virtual Sapele_NewsTb Sapele_NewsTb { get; set; }
    public virtual SportTb SportTb { get; set; }
    public virtual VideoTb VideoTb { get; set; }
    public virtual RegistrationTb RegistrationTb { get; set; }
    public virtual AllNewsTb AllNewsTb { get; set; }
    public virtual commentTb commentTb { get; set; }
    public virtual FollowTb FollowTb { get; set; }
    public virtual messageTb messageTb { get; set; }
    public virtual NewsPostTb NewsPostTb { get; set; }
    public virtual NotificationTB NotificationTB { get; set; }
    public virtual UserTb UserTb { get; set; }
}

public partial class FollowTb
{
    public FollowTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int FollowID { get; set; }
    public string username { get; set; }
    public string Her_Comment { get; set; }
    public string His_comment { get; set; }
    public string client_comment { get; set; }
    public string body_commet { get; set; }
    public string Url { get; set; }
    public string FollowUserID { get; set; }
    public string Other_isues { get; set; }
    public string Date_Time { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class HealthTb
{
    public HealthTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int Health_and_True_Life_StoryID { get; set; }
    public string Photo { get; set; }
    public string Video { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string Admin_Photo { get; set; }
    public string Admin_Name { get; set; }
    public string Time_and_Date { get; set; }
    public string Likes_and_comments { get; set; }
    public string Views { get; set; }
    public string Health_and_True_Life_StoryTbID { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class messageTb
{
    public messageTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int MessageID { get; set; }
    public string username { get; set; }
    public string Her_Comment { get; set; }
    public string His_comment { get; set; }
    public string client_comment { get; set; }
    public string body_commet { get; set; }
    public string Url { get; set; }
    public string MessageTbID { get; set; }
    public string Other_isues { get; set; }
    public string Date_Time { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class NewsPostTb
{
    public NewsPostTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int NewsPostID { get; set; }
    public string username { get; set; }
    public string Her_Comment { get; set; }
    public string His_comment { get; set; }
    public string client_comment { get; set; }
    public string body_commet { get; set; }
    public string Url { get; set; }
    public string NewsPostTbID { get; set; }
    public string Other_isues { get; set; }
    public string Date_Time { get; set; }
    public string Photo { get; set; }
    public string Photo2 { get; set; }
    public string Photo3 { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class NotificationTB
{
    public NotificationTB()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int NotificationID { get; set; }
    public string username { get; set; }
    public string Her_Comment { get; set; }
    public string His_comment { get; set; }
    public string client_comment { get; set; }
    public string body_commet { get; set; }
    public string Url { get; set; }
    public string NotificationTbID { get; set; }
    public string Other_isues { get; set; }
    public string Date_Time { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class PoliticsTb
{
    public PoliticsTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int PoliticsID { get; set; }
    public string Photo { get; set; }
    public string Video { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string Admin_Photo { get; set; }
    public string Admin_Name { get; set; }
    public string Time_and_Date { get; set; }
    public string Likes_and_comments { get; set; }
    public string Views { get; set; }
    public string PoliticsTbID { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class QuotesTb
{
    public QuotesTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int Wisdom_QuotesID { get; set; }
    public string Photo { get; set; }
    public string Video { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string Admin_Photo { get; set; }
    public string Admin_Name { get; set; }
    public string Time_and_Date { get; set; }
    public string Likes_and_comments { get; set; }
    public string Views { get; set; }
    public string WisdomQuoteTbID { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class RegistrationTb
{
    public RegistrationTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int RegistrationID { get; set; }
    public string First_Name { get; set; }
    public string Last_name { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string RegisterID { get; set; }
    public string Time_date { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class Sapele_NewsTb
{
    public Sapele_NewsTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int Sapele_NewsID { get; set; }
    public string Photo { get; set; }
    public string Video { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string Admin_Photo { get; set; }
    public string Admin_Name { get; set; }
    public string Time_and_Date { get; set; }
    public string Likes_and_comments { get; set; }
    public string Views { get; set; }
    public string Sapele_NewsTbID { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class SportTb
{
    public SportTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int SportID { get; set; }
    public string Photo { get; set; }
    public string Video { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string Admin_Photo { get; set; }
    public string Admin_Name { get; set; }
    public string Time_and_Date { get; set; }
    public string Likes_and_comments { get; set; }
    public string Sport_Views { get; set; }
    public string SportTbID { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class UserTb
{
    public UserTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int Users { get; set; }
    public string username { get; set; }
    public string Her_Comment { get; set; }
    public string His_comment { get; set; }
    public string client_comment { get; set; }
    public string body_commet { get; set; }
    public string Url { get; set; }
    public string UserChatId { get; set; }
    public string Other_isues { get; set; }
    public string Date_Time { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}

public partial class VideoTb
{
    public VideoTb()
    {
        this.Connection_Tb = new HashSet<Connection_Tb>();
    }

    public int VideosID { get; set; }
    public string Video { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public string Admin_Photo { get; set; }
    public string Admin_Name { get; set; }
    public string Time_and_Date { get; set; }
    public string Likes_and_comments { get; set; }
    public string Views { get; set; }
    public string VideoTbID { get; set; }

    public virtual ICollection<Connection_Tb> Connection_Tb { get; set; }
}
